### ISSUE TITLE
Error 500 (NullPointerException) when processing OriginBatch with a null lastName

### ISSUE THREAD

**Issue by namsor** [namsor/namsor-python-sdk2#1]
Processing a batch request with a null lastName results in an API 500 error,
```

 java.lang.NullPointerException
        at com.namsor.api2.classify.AIParsedNameOriginCountryClassifier.features(AIParsedNameOriginCountryClassifier.java:106)
        at com.namsor.api2.classify.AIClassifier.classifyDetailsFact(AIClassifier.java:272)
        at com.namsor.api2.classify.AI.predictOrigin(AI.java:349)

```
The API should process all other names and return a null origin for the name where lastName is null.

**Comment by namsor** [comment]
Fixed : now returns null origin, originAlt in that case.
